# Generated by Django 5.2.7 on 2025-10-20 04:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('qty', models.DecimalField(decimal_places=10, max_digits=30)),
                ('aggressor_side', models.CharField(max_length=4)),
                ('maker_order_id', models.CharField(max_length=64)),
                ('taker_order_id', models.CharField(max_length=64)),
            ],
        ),
    ]
